# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hzhzhz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        Form.setMinimumSize(QtCore.QSize(1000, 800))
        Form.setMaximumSize(QtCore.QSize(1000, 800))
        Form.setStyleSheet("background-color: rgb(245, 244, 255);")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 970, 670))
        self.tableWidget.setMinimumSize(QtCore.QSize(970, 670))
        self.tableWidget.setMaximumSize(QtCore.QSize(970, 670))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: rgb(134, 255, 225);\n"
"alternate-background-color: rgb(234, 250, 255);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(157)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(62)
        self.tableWidget.verticalHeader().setMinimumSectionSize(62)
        self.tBtn_minimaze = QtWidgets.QToolButton(Form)
        self.tBtn_minimaze.setGeometry(QtCore.QRect(900, 10, 45, 30))
        self.tBtn_minimaze.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_minimaze.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_minimaze.setFont(font)
        self.tBtn_minimaze.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_minimaze.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_minimaze.setObjectName("tBtn_minimaze")
        self.tBtn_closeWindow = QtWidgets.QToolButton(Form)
        self.tBtn_closeWindow.setGeometry(QtCore.QRect(950, 10, 45, 30))
        self.tBtn_closeWindow.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_closeWindow.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tBtn_closeWindow.setFont(font)
        self.tBtn_closeWindow.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_closeWindow.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_closeWindow.setObjectName("tBtn_closeWindow")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 880, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.btn_enter = QtWidgets.QPushButton(Form)
        self.btn_enter.setGeometry(QtCore.QRect(390, 730, 211, 65))
        self.btn_enter.setMinimumSize(QtCore.QSize(211, 65))
        self.btn_enter.setMaximumSize(QtCore.QSize(211, 65))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.btn_enter.setFont(font)
        self.btn_enter.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButtonn:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        self.btn_enter.setObjectName("btn_enter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название фильма"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Жанр фильма"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Год выхода"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Страна"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Жанр"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Описание"))
        self.tBtn_minimaze.setText(_translate("Form", "_"))
        self.tBtn_closeWindow.setText(_translate("Form", "X"))
        self.label.setText(_translate("Form", "Топ 1000 лучших фильмов"))
        self.btn_enter.setText(_translate("Form", "Следующие 10 фильмов"))
